main: com.cavetale.money.MoneyPlugin
name: Money
description: Money management
author: StarTux
version: 0.1
api-version: 1.18
website: https://github.com/StarTux/Money
depend: [Core, SQL, PlayerCache, Sidebar]
softdepend: [Vault]

commands:

  money:
    aliases: [bal, balance, eco, account, acc]
    description: Player Interface
    permission: money.money
    usage: /money

  moneyadmin:
    aliases: []
    description: Admin Interface
    permission: money.admin
    usage: /moneyadmin

permissions:

  money.money:
    description: use /money
    default: op

  money.admin:
    description: Use admin commands
    default: op