main: com.cavetale.money.MoneyPlugin
name: Money
description: Money management
author: StarTux
version: 0.1
api-version: 1.13
website: https://github.com/StarTux/Money
depend: [SQL, GenericEvents]
softdepend: []
commands:
  money:
    aliases: []
    description: money
    permission: money.money
    usage: |-
      Usage:
      /money - Check your bank account
permissions:
  money.money:
    description: use /money
    default: op
  money.admin:
    description: Use admin commands
    default: op
