name: Money
description: Money management
author: StarTux
version: 0.1
website: http://cavetale.com
main: com.cavetale.money.MoneyPlugin
depend: [SQL, PlayerCache, GenericEvents]
softdepend: [Essentials, EssentialsX]
commands:
  money:
    aliases: [bal,eco,econ]
    description: Bank account command interface.
    permission: money.money
    usage: 'Usage: /money - Check your bank account.'
  pay:
    aliases: []
    description: Send someone money.
    permission: money.money
    usage: 'Usage: /pay <player> <amount>'
permissions:
  money.money:
    description: use /money
    default: op
  money.admin:
    description: Use admin commands
    default: op
