main: com.cavetale.money.MoneyPlugin
name: Money

version: 0.1
api-version: 1.18

description: Money management
author: StarTux
website: https://github.com/StarTux/Money

depend: [Core, SQL, PlayerCache, Mytems]
softdepend: [Vault]

commands:

  money:
    aliases: [bal, balance, eco, account, acc]
    description: Player Interface
    permission: money.money
    usage: /money

  moneyadmin:
    aliases: [moneyadm]
    description: Admin Interface
    permission: money.admin
    usage: /moneyadmin

permissions:

  money.money:
    description: use /money
    default: op

  money.top:
    description: use /money top
    default: op

  money.log:
    description: use /money log
    default: op

  money.send:
    description: use /money send
    default: op

  money.other:
    description: use /money <player> on other players
    default: op

  money.player:
    description: All player permissions
    default: false
    children:
      money.money: true
      money.top: true
      money.log: true
      money.send: true

  money.admin:
    description: Use admin commands
    default: op
